apiVersion: v1
kind: PersistentVolume
metadata:
  name: fc-pv
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: filecache.csi.aws.com
    volumeHandle: fc-052e0e05e02430ef2
    volumeAttributes:
      dnsname: fc-052e0e05e02430ef2.fsx.us-east-1.amazonaws.com
      mountname: r473jbev
